### ISSUE TITLE
No colors on stdout

### ISSUE THREAD

**Issue by pmendelski** [stefanmaric/ntee#1]
Hi,
Thanks for this tool.

I have a following problem.
When I execute `mocha` there are colors on stdout.

Although when I execute:

``` sh
mocha | ntee ./build/test-report.txt
```

colors are missing.

**Comment by stefanmaric** [comment]
Hi @mendlik ,

That behavior is not handled by `ntee` itself. Mocha, as many terminal utils, suppresses coloring when piping its output.

You can find many answered questions like this: http://unix.stackexchange.com/questions/19317/can-less-retain-colored-output

``` bash
$ ls | tee list.txt
$ ls | ntee nlist.txt
```

Is not the same as:

``` bash
$ ls --color=always | tee list.txt
$ ls --color=always | ntee nlist.txt
```

Try to use Mocha's `-c / --colors` option: https://mochajs.org/#usage

It should give you what you want, but be aware that your files will also have the escape characters that produce the coloring. If you `cat` them, the output will be colored as well, but that's probably a major drawback.

You probably want to remove the escape chars from your file: http://stackoverflow.com/questions/17998978/removing-colors-from-output

Hopefully this helps you to address your issue.

Regards,

**Comment by pmendelski** [comment]
Hi,

Thank you for your comprehensive answer.

Adding `--colors` parameter solved the problem.
As you pointed out it also led to the problem of escaping characters in the text file.
One more time thanks for explanation.

Finally I gave up piping mocha's output, because pipes also overrides mocha's process exit code.
Nevertheless your module works seamlessly.

Regards
